apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 375728455575.dkr.ecr.us-west-1.amazonaws.com/frontend:3
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://k8s-threetie-mainlb-1dd958d0ec-1838627282.us-west-1.elb.amazonaws.com/api/tasks"           #"http://api:3500/api/tasks"
        ports:
        - containerPort: 3000
